import { TTodos } from "./types";

export const defaultTodos: TTodos = [
    { "id": "1", "title": "Check Visa Requirements", "description": "Confirm the specific visa and residence permit requirements for your home country on the German embassy website.", "completed": false, "category": "Before Arrival", "dueDate": null },
    { "id": "2", "title": "Apply for Student Visa", "description": "Book and attend your visa appointment at the German embassy or consulate well in advance of your travel date.", "completed": false, "category": "Before Arrival", "dueDate": "2025-07-20" },
    { "id": "3", "title": "Open a Blocked Account", "description": "Initiate the process to set up your blocked account to prove financial means for your visa application.", "completed": false, "category": "Before Arrival", "dueDate": "2025-07-25" },
    { "id": "4", "title": "Transfer Funds", "description": "Transfer the required amount of money to your blocked account as soon as possible.", "completed": false, "category": "Before Arrival", "dueDate": "2025-07-30" },
    { "id": "5", "title": "Research Health Insurance", "description": "Look into German statutory health insurance providers and secure a confirmation for your enrollment.", "completed": false, "category": "Before Arrival", "dueDate": "2025-08-01" },
    { "id": "6", "title": "Apply for Dormitory", "description": "Submit your application for a student dormitory through the Studierendenwerk portal.", "completed": false, "category": "Before Arrival", "dueDate": "2025-08-05" },
    { "id": "7", "title": "Look for Private Housing", "description": "If you don't secure a dorm spot, explore private housing options on websites like WG-Gesucht.", "completed": false, "category": "Before Arrival", "dueDate": "2025-08-15" },
    { "id": "8", "title": "Secure a Lease Agreement", "description": "Sign your rental agreement for your new home, either in a dorm or private apartment.", "completed": false, "category": "Before Arrival", "dueDate": "2025-08-20" },
    { "id": "9", "title": "Gather Enrollment Documents", "description": "Collect and scan all documents required for your university enrollment via the PLUS-Portal.", "completed": false, "category": "Before Arrival", "dueDate": "2025-08-25" },
    { "id": "10", "title": "Pay Semester Fee", "description": "Pay your semester fee and social contribution to finalize your university enrollment.", "completed": false, "category": "Before Arrival", "dueDate": "2025-08-30" },
    { "id": "11", "title": "Book Your Flight", "description": "Purchase your flight to Germany, keeping your arrival date in mind.", "completed": false, "category": "Before Arrival", "dueDate": "2025-09-01" },
    { "id": "12", "title": "Plan Train to Hildesheim", "description": "Plan your train travel from your arrival airport to Hildesheim Hauptbahnhof (main train station).", "completed": false, "category": "Before Arrival", "dueDate": "2025-09-05" },
    { "id": "13", "title": "Get a German SIM Card", "description": "Upon arrival, purchase a German SIM card to stay connected.", "completed": false, "category": "Upon Arrival", "dueDate": "2025-09-10" },
    { "id": "14", "title": "Get Landlord's Confirmation", "description": "Get the signed Wohnungsgeberbestätigung from your landlord or dorm administrator. This is crucial for registration.", "completed": false, "category": "Upon Arrival", "dueDate": "2025-09-15" },
    { "id": "15", "title": "Book City Registration", "description": "Schedule your Anmeldung appointment online on the Hildesheim city website.", "completed": false, "category": "Upon Arrival", "dueDate": "2025-09-18" },
    { "id": "16", "title": "Attend Anmeldung Appointment", "description": "Go to the Bürgerbüro with your passport, visa, and the Wohnungsgeberbestätigung.", "completed": false, "category": "Upon Arrival", "dueDate": "2025-09-22" },
    { "id": "17", "title": "Open a German Bank Account", "description": "Visit a bank to open a student account using your new Anmeldebestätigung.", "completed": false, "category": "Upon Arrival", "dueDate": "2025-09-25" },
    { "id": "18", "title": "Pay Public Broadcasting Fee", "description": "Register and pay the Rundfunkbeitrag (TV/radio fee) for your household.", "completed": false, "category": "Settling In", "dueDate": "2025-10-01" },
    { "id": "19", "title": "Apply for Residence Permit", "description": "Book an appointment at the Ausländerbehörde (Foreigners' Office) to convert your visa into a residence permit.", "completed": false, "category": "Settling In", "dueDate": "2025-10-07" },
    { "id": "20", "title": "Activate University Accounts", "description": "Log in to your UNI-Account and other university platforms like Stud.IP and the webmail service.", "completed": false, "category": "Settling In", "dueDate": "2025-10-10" },
    { "id": "21", "title": "Get Digital Semester Ticket", "description": "Follow the university's instructions to download and activate your Deutschlandsemesterticket.", "completed": false, "category": "Settling In", "dueDate": "2025-10-15" },
    { "id": "22", "title": "Find Your Grocery Stores", "description": "Locate the nearest supermarkets like REWE, Edeka, and Aldi to your home.", "completed": false, "category": "Settling In", "dueDate": "2025-10-17" },
    { "id": "23", "title": "Explore the City", "description": "Take some time to explore the city center and get familiar with the bus system.", "completed": false, "category": "Settling In", "dueDate": "2025-10-20" },
    { "id": "24", "title": "Visit the International Office", "description": "Stop by the International Office to introduce yourself and ask any remaining questions.", "completed": false, "category": "Settling In", "dueDate": "2025-10-25" },
    { "id": "25", "title": "Join a Student Club", "description": "Explore the various student clubs and organizations at the university and join one that aligns with your interests.", "completed": false, "category": "Settling In", "dueDate": "2025-10-31" }
];
